"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Loader2,ShieldCheck} from "lucide-react";
import {loadProspects,upsertProspect,type WorkspaceProspect} from "@/lib/workspace";
import BusinessDemo from "./BusinessDemo";
export default function DemoFactoryPage(){
 const [prospect,setProspect]=useState<WorkspaceProspect|null>(null),[from,setFrom]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{const p=new URLSearchParams(window.location.search),id=p.get("prospect");setFrom(p.get("from")||"");const found=id?loadProspects().find(x=>x.id===id)||null:null;setProspect(found);setLoading(false);if(found&&!found.intelligence){fetch("/api/intelligence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({placeId:found.id,name:found.name,category:found.category,address:found.location,website:found.website,mapsUrl:found.mapsUrl,phone:found.phone,photoNames:found.mapsPhotoNames||[],imageUrls:found.imageUrls||[],rating:found.rating,reviewCount:found.reviewCount,hours:found.hours,reviews:found.reviews||[]})}).then(r=>r.ok?r.json():null).then(d=>{if(d?.intelligence){const next={...found,intelligence:d.intelligence,rating:d.intelligence.maps?.rating||found.rating,reviewCount:d.intelligence.maps?.reviewCount||found.reviewCount,hours:d.intelligence.maps?.hours||found.hours,reviews:d.intelligence.reviews||found.reviews,mapsPhotoNames:[...(found.mapsPhotoNames||[]),...(d.intelligence.maps?.photos||[])]};upsertProspect(next);setProspect(next)}}).catch(()=>{})}},[]);
 const back=from==="discovery"?"/discovery":"/sales";
 return <main style={{minHeight:"100vh",background:"#f8fafc"}}>{loading?<div style={{padding:80,textAlign:"center",color:"#667085"}}><Loader2 className="spin" size={20}/> Loading business demo…</div>:prospect?<><div style={{height:44,background:"#fff",borderBottom:"1px solid #e4e7ec",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px",position:"relative",zIndex:60}}><Link href={back} style={{fontSize:11,color:"#667085",textDecoration:"none"}}><ArrowLeft size={13} style={{verticalAlign:"-2px",marginRight:5}}/>Back</Link><span style={{fontSize:10,color:"#027a48",fontWeight:800}}><ShieldCheck size={12} style={{verticalAlign:"-2px",marginRight:4}}/>Owner approval required</span></div><BusinessDemo initialProspect={prospect}/></>:<div style={{padding:80,textAlign:"center",color:"#667085"}}>Prospect not found. Return to Discovery and create the demo again.</div>}</main>
}
