"use client";
import { useState } from "react";
import { CheckCircle2, ExternalLink, FileText, MapPin, MessageCircle, Phone, Sparkles, Target, ChevronRight } from "lucide-react";
import { createLead } from "@/lib/businessos";
import type { WorkspaceProspect } from "@/lib/workspace";

const initials=(n:string)=>n.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()||"B";
const pretty=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function ProspectWebsite({prospect}:{prospect:WorkspaceProspect|null}){
 const [customer,setCustomer]=useState(""),[phone,setPhone]=useState(""),[need,setNeed]=useState(""),[submitted,setSubmitted]=useState(false),[leadId,setLeadId]=useState(""),[error,setError]=useState("");
 const name=prospect?.name||"Your Business",category=prospect?.category||"local business",location=prospect?.location||"Your local market",hasWebsite=Boolean(prospect?.website),realEstate=/real|property|estate/i.test(category),appointment=/dental|dentist|doctor|clinic|salon|spa/i.test(category)||prospect?.demoType==="appointment",action=appointment?"Request an appointment":realEstate?"Request property details":"Send an enquiry",hero=prospect?.imageUrls?.[0],mapsPhotos=(prospect?.mapsPhotoNames||[]).slice(0,6).map(x=>`/api/place-photo?name=${encodeURIComponent(x)}`),images=[...(prospect?.imageUrls||[]),...mapsPhotos].filter((x,i,a)=>a.indexOf(x)===i).slice(0,8);
 function submit(){setError("");if(!customer.trim()||!phone.trim()){setError("Please enter your name and mobile number.");return}const l=createLead({name:customer.trim(),phone:phone.trim(),intent:need.trim()?`${appointment?"Appointment":realEstate?"Property":"Customer"} enquiry · ${need.trim()}`:`${appointment?"Appointment":realEstate?"Property":"Customer"} enquiry`,channel:"Demo",status:"New",prospectId:prospect?.id,businessName:name,location});setLeadId(l.id);setSubmitted(true)}
 const nav=["Home","About","Highlights","Gallery","Location","Enquiry"];
 return <div style={{background:"#f6f8fb",color:"#101828",fontFamily:"DM Sans,system-ui,sans-serif"}}>
  <nav style={{position:"sticky",top:0,zIndex:10,background:"rgba(255,255,255,.94)",backdropFilter:"blur(12px)",borderBottom:"1px solid #e4e7ec",padding:"0 22px"}}><div style={{maxWidth:1180,margin:"auto",height:68,display:"flex",alignItems:"center",justifyContent:"space-between",gap:18}}><div style={{display:"flex",alignItems:"center",gap:9}}><div style={{width:40,height:40,borderRadius:11,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#2e90fa,#175cd3)",color:"white",fontWeight:900}}>{initials(name)}</div><strong style={{fontSize:13}}>{name}</strong></div><div style={{display:"flex",gap:18,alignItems:"center"}}>{nav.map(x=><a key={x} href={`#${x.toLowerCase()}`} style={{fontSize:10,color:"#667085",textDecoration:"none"}}>{x}</a>)}<a href="#enquiry" style={{background:"#175cd3",color:"white",padding:"10px 13px",borderRadius:9,fontSize:10,fontWeight:900,textDecoration:"none"}}>{action}</a></div></div></nav>
  <section id="home" style={{position:"relative",overflow:"hidden",background:"#08111f",color:"white"}}><div style={{position:"absolute",inset:0,backgroundImage:hero?`linear-gradient(90deg,rgba(8,17,31,.97),rgba(8,17,31,.70) 55%,rgba(8,17,31,.30)),url(${hero})`:"linear-gradient(135deg,#08111f,#172554)",backgroundSize:"cover",backgroundPosition:"center"}}/><div style={{position:"relative",maxWidth:1180,margin:"auto",padding:"88px 22px",display:"grid",gridTemplateColumns:"1.1fr .9fr",gap:45,alignItems:"center"}}><div><div style={{fontSize:10,color:"#84caff",fontWeight:900,letterSpacing:".17em"}}>{pretty(category).toUpperCase()} · {location.toUpperCase()}</div><h1 style={{fontFamily:"Manrope",fontSize:"clamp(44px,6vw,72px)",lineHeight:.98,letterSpacing:"-.055em",margin:"16px 0 20px"}}>A better digital front door for <span style={{color:"#84caff"}}>{name}</span>.</h1><p style={{fontSize:16,lineHeight:1.7,color:"#d0d5dd",maxWidth:650}}>A polished website concept generated from the business context already discoverable publicly.</p><a href="#enquiry" style={{display:"inline-flex",alignItems:"center",gap:6,marginTop:28,background:"#175cd3",color:"white",padding:"13px 17px",borderRadius:10,fontWeight:900,fontSize:12,textDecoration:"none"}}>{action}<ChevronRight size={14}/></a></div><div style={{background:"rgba(255,255,255,.08)",border:"1px solid rgba(255,255,255,.14)",borderRadius:22,padding:12}}>{hero?<img src={hero} alt={name} onError={e=>e.currentTarget.style.display="none"} style={{width:"100%",height:370,objectFit:"cover",borderRadius:16}}/>:<div style={{height:370,borderRadius:16,display:"grid",placeItems:"center",background:"linear-gradient(135deg,#172554,#1e293b)",fontSize:78,fontWeight:900,color:"#93c5fd"}}>{initials(name)}</div>}<div style={{padding:"12px 5px 2px",fontSize:10,color:"#cbd5e1",display:"flex",justifyContent:"space-between"}}><span>{hasWebsite?"Website improvement concept":"New website opportunity"}</span><strong style={{color:"#86efac"}}>Live demo</strong></div></div></div></section>
  <section id="about" style={{padding:"82px 22px",background:"white"}}><div style={{maxWidth:1180,margin:"auto",display:"grid",gridTemplateColumns:".85fr 1.15fr",gap:70}}><div><small style={eyebrow}>ABOUT THE BUSINESS</small><h2 style={h2}>Make the business easier to discover, trust and contact.</h2></div><div><p style={p}>This concept uses verified prospect context — business name, category, location and available contact details. It does not invent services, prices, reviews or claims.</p><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:12,marginTop:28}}>{[[MapPin,"Local presence",location],[Phone,"Direct contact",prospect?.phone||"Not returned by Maps"],[FileText,"Website status",hasWebsite?"Existing website":"No website returned"],[Target,"Recommended",prospect?.recommendedService||"New website + lead capture"]].map(([I,t,v])=>{const Icon=I as any;return <div key={String(t)} style={tile}><Icon size={17} color="#175cd3"/><div style={small}>{String(t)}</div><strong style={{fontSize:12}}>{String(v)}</strong></div>})}</div></div></div></section>
  <section id="highlights" style={{padding:"82px 22px",background:"#f8fafc"}}><div style={{maxWidth:1180,margin:"auto"}}><div style={{textAlign:"center",maxWidth:720,margin:"auto"}}><small style={eyebrow}>HIGHLIGHTS</small><h2 style={h2}>A complete customer journey, not a landing page.</h2><p style={p}>Multiple scrollable sections make this feel like a real website the owner can experience during the sales conversation.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:16,marginTop:40}}>{[[Sparkles,"Premium first impression","Brand mark, hero imagery and a clear primary action."],[MessageCircle,"Lead capture","The enquiry flow connects directly to BusinessOS."],[MapPin,"Local trust","Location, contact and Maps context stay visible."]].map(([I,t,d])=>{const Icon=I as any;return <div key={String(t)} style={{background:"white",border:"1px solid #e4e7ec",borderRadius:18,padding:25,minHeight:160}}><div style={{width:42,height:42,borderRadius:11,background:"#eff8ff",display:"grid",placeItems:"center"}}><Icon size={19} color="#175cd3"/></div><h3 style={{fontFamily:"Manrope",fontSize:17,margin:"18px 0 7px"}}>{String(t)}</h3><p style={{...p,fontSize:12,margin:0}}>{String(d)}</p></div>})}</div></div></section>
  <section id="gallery" style={{padding:"82px 22px",background:"#101828",color:"white"}}><div style={{maxWidth:1180,margin:"auto"}}><small style={{...eyebrow,color:"#84caff"}}>VISUAL STORY</small><h2 style={{...h2,color:"white",maxWidth:760}}>Use the business's real visual context.</h2><p style={{color:"#98a2b3",fontSize:12,maxWidth:700,lineHeight:1.6}}>Public website images are used when available. Maps photos become visual material when the business has no usable website gallery.</p>{images.length?<div style={{display:"grid",gridTemplateColumns:"1.35fr .65fr .65fr",gridAutoRows:"220px",gap:10,marginTop:32}}>{images.map((src,i)=><div key={src} style={{gridRow:i===0?"span 2":undefined,borderRadius:16,overflow:"hidden",background:"#1d2939"}}><img src={src} alt={`${name} visual ${i+1}`} onError={e=>e.currentTarget.style.display="none"} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div>)}</div>:<div style={{marginTop:30,border:"1px dashed #475467",borderRadius:16,padding:50,textAlign:"center",color:"#98a2b3"}}>No usable public images were returned. Gallery is ready for owner-approved photography.</div>}</div></section>
  <section id="location" style={{padding:"82px 22px",background:"white"}}><div style={{maxWidth:1180,margin:"auto",display:"grid",gridTemplateColumns:"1fr 1fr",gap:30}}><div style={{minHeight:390,borderRadius:22,overflow:"hidden",background:"#0b1220"}}>{mapsPhotos[0]?<img src={mapsPhotos[0]} alt="Maps business photo" onError={e=>e.currentTarget.style.display="none"} style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<div style={{height:390,display:"grid",placeItems:"center",color:"#93c5fd"}}><MapPin size={82}/></div>}</div><div style={{padding:"25px 5px"}}><small style={eyebrow}>FIND US</small><h2 style={h2}>Local, visible and easy to reach.</h2><p style={p}>{location}</p>{prospect?.phone&&<p style={{fontWeight:800,fontSize:13}}><Phone size={15} color="#175cd3"/> {prospect.phone}</p>}<div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:25}}>{prospect?.mapsUrl&&<a href={prospect.mapsUrl} target="_blank" rel="noreferrer" style={primary}><MapPin size={13}/> Open Google Maps</a>}{hasWebsite&&prospect?.website&&<a href={prospect.website} target="_blank" rel="noreferrer" style={secondary}><ExternalLink size={13}/> Current website</a>}</div></div></div></section>
  <section id="enquiry" style={{padding:"88px 22px",background:"linear-gradient(135deg,#eff8ff,#fff 55%,#f5f3ff)"}}><div style={{maxWidth:900,margin:"auto",background:"white",border:"1px solid #e4e7ec",borderRadius:24,padding:34,boxShadow:"0 20px 60px rgba(16,24,40,.08)"}}><div style={{textAlign:"center"}}><small style={eyebrow}>START A CONVERSATION</small><h2 style={h2}>{action}</h2><p style={p}>A working enquiry flow for the sales demo. Submitted leads are captured into SolProvo BusinessOS.</p></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginTop:28}}><div><label style={label}>Your name</label><input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Full name" style={field}/></div><div><label style={label}>Mobile number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="10-digit mobile number" style={field}/></div><div style={{gridColumn:"1/-1"}}><label style={label}>{realEstate?"What are you looking for?":"What do you need?"}</label><textarea value={need} onChange={e=>setNeed(e.target.value)} rows={5} placeholder={realEstate?"e.g. 2/3 BHK, plot, commercial, budget…":"Tell the business what you need…"} style={{...field,resize:"vertical"}}/></div>{error&&<div style={{gridColumn:"1/-1",background:"#fff1f0",color:"#b42318",padding:10,borderRadius:8,fontSize:11}}>{error}</div>}<button onClick={submit} style={{gridColumn:"1/-1",border:0,background:"#175cd3",color:"white",padding:14,borderRadius:10,fontWeight:900,cursor:"pointer"}}>{action}</button></div>{submitted&&<div style={{marginTop:14,padding:13,borderRadius:10,background:"#ecfdf3",color:"#027a48",fontSize:11}}><CheckCircle2 size={15}/> <strong>Lead captured.</strong> BusinessOS reference: {leadId.slice(-8)}</div>}</div></section>
  <footer style={{background:"#08111f",color:"#98a2b3",padding:"32px 22px"}}><div style={{maxWidth:1180,margin:"auto",display:"flex",justifyContent:"space-between",alignItems:"center",gap:20}}><div style={{display:"flex",gap:10,alignItems:"center"}}><div style={{width:36,height:36,borderRadius:10,display:"grid",placeItems:"center",background:"#175cd3",color:"white",fontWeight:900}}>{initials(name)}</div><strong style={{color:"white",fontSize:12}}>{name}</strong></div><span style={{fontSize:9}}>Demo content is illustrative. Owner approval required before production publishing.</span></div></footer>
 </div>
}
const eyebrow:React.CSSProperties={fontSize:10,color:"#175cd3",fontWeight:900,letterSpacing:".15em"};const h2:React.CSSProperties={fontFamily:"Manrope,system-ui",fontSize:"clamp(32px,4vw,48px)",lineHeight:1.05,letterSpacing:"-.045em",margin:"12px 0 18px"};const p:React.CSSProperties={fontSize:15,lineHeight:1.75,color:"#667085"};const small:React.CSSProperties={fontSize:10,color:"#667085",margin:"10px 0 4px"};const tile:React.CSSProperties={border:"1px solid #e4e7ec",borderRadius:14,padding:17};const label:React.CSSProperties={fontSize:10,fontWeight:800,color:"#475467",display:"block",marginBottom:6};const field:React.CSSProperties={width:"100%",boxSizing:"border-box",border:"1px solid #d0d5dd",borderRadius:9,padding:12,fontSize:12};const primary:React.CSSProperties={display:"inline-flex",gap:6,alignItems:"center",background:"#175cd3",color:"white",padding:"12px 15px",borderRadius:9,textDecoration:"none",fontSize:11,fontWeight:800};const secondary:React.CSSProperties={display:"inline-flex",gap:6,alignItems:"center",border:"1px solid #d0d5dd",color:"#344054",padding:"11px 15px",borderRadius:9,textDecoration:"none",fontSize:11,fontWeight:700};
