import {PROFILES,MODES} from './profiles.js';
import {scoreAnswer,chooseFollowUp,readiness} from './engine.js';

const $=id=>document.getElementById(id);let role='librarian',mode='realistic',index=0,answers=[],stream=null,recognition=null,listening=false,started=0,timer=null,currentFinal='';
const storageKey='interview-os-sessions-v1';
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function setup(){
 $('roles').innerHTML=Object.entries(PROFILES).map(([k,v])=>`<button class="option ${k===role?'selected':''}" data-role="${k}"><b>${v.name}</b><span>${v.subtitle}</span></button>`).join('');
 $('modes').innerHTML=Object.entries(MODES).map(([k,v])=>`<button class="option ${k===mode?'selected':''}" data-mode="${k}"><b>${v.name}</b><span>${v.desc}</span></button>`).join('');
 document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;setup()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;setup()});
 $('start').onclick=start;$('reset').onclick=reset;$('repeat').onclick=()=>speak($('question').textContent);$('answer').onclick=()=>listening?stopAnswer():startAnswer();$('retry').onclick=retryWeak;
}
async function start(){index=0;answers=[];$('roleTitle').textContent=PROFILES[role].name;$('modeTitle').textContent=MODES[mode].name+' · '+MODES[mode].desc;$('status').textContent='Live';show('live');
 try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$('video').srcObject=stream;$('cameraMsg').style.display='none';$('face').textContent='Available';}catch{$('cameraMsg').style.display='block';$('face').textContent='Unavailable'}
 ask();
}
function reset(){cleanup();show('setup');$('status').textContent='Ready';setup()}
function cleanup(){if(stream)stream.getTracks().forEach(t=>t.stop());if(timer)clearInterval(timer);if(recognition)try{recognition.stop()}catch{}listening=false}
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=mode==='pressure'?1:.9;speechSynthesis.speak(u)}
function ask(){const q=PROFILES[role].questions[index];if(!q)return finish();$('counter').textContent=`Question ${index+1} / ${PROFILES[role].questions.length}`;$('bar').style.width=`${index/PROFILES[role].questions.length*100}%`;$('question').textContent=q[0];$('transcript').textContent='Press “Start answering” and speak naturally.';$('hint').textContent=mode==='pressure'?'Keep the answer concise. Lead with your decision, then justify it.':'Take a short pause before answering. Structure beats speed.';$('thinking').textContent='●';speak(q[0])}
function startAnswer(){currentFinal='';started=Date.now();listening=true;$('answer').textContent='Stop answering';$('speech').textContent='Listening';timer=setInterval(()=>$('timer').textContent=fmt(Date.now()-started),250);
 const C=window.SpeechRecognition||window.webkitSpeechRecognition;if(!C){$('transcript').textContent='Speech recognition is unavailable. Speak your answer aloud, then press Stop and enter your answer if your browser provides a prompt.';return}
 recognition=new C();recognition.lang='en-IN';recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?currentFinal+=t+' ':interim+=t}$('transcript').textContent=(currentFinal+interim).trim()||'Listening…'};recognition.onend=()=>{if(listening)try{recognition.start()}catch{}};try{recognition.start()}catch{} }
function stopAnswer(){listening=false;if(recognition)try{recognition.stop()}catch{}if(timer)clearInterval(timer);const text=($('transcript').textContent||'').trim();const duration=(Date.now()-started)/1000;const q=PROFILES[role].questions[index];const safe=text.startsWith('Press “Start')?'':text;answers.push({question:q[0],text:safe,duration,score:scoreAnswer(safe,q[0],q[1],duration)});$('timer').textContent='00:00';$('speech').textContent='Captured';$('answer').textContent='Start answering';index++;setTimeout(ask,450)}
function fmt(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function finish(){cleanup();const valid=answers.filter(a=>a.text);const overall=readiness(valid.map(a=>a.score));const scores=valid.length?valid:answers;localStorage.setItem(storageKey,JSON.stringify({date:new Date().toISOString(),role,mode,overall,answers:scores}));$('overall').textContent=overall;$('headline').textContent=overall>=85?'Strong interview readiness.':overall>=70?'Good foundation — sharpen the weak dimensions.':'A clear improvement path is ready for your next session.';$('reportMeta').textContent=`${PROFILES[role].name} · ${answers.length} questions · ${MODES[mode].name} mode`;
 const dims=['relevance','knowledge','structure','specificity','communication','completeness'];$('scores').innerHTML=dims.map(k=>{const v=valid.length?Math.round(valid.reduce((s,a)=>s+a.score.dimensions[k],0)/valid.length):0;const label={relevance:'Relevance',knowledge:'Subject knowledge',structure:'Structure',specificity:'Specificity & evidence',communication:'Communication',completeness:'Completeness'}[k];return `<div class="score"><div class="scoreline"><span>${label}</span><b>${v}/100</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`}).join('');
 const ranked=[...valid].sort((a,b)=>a.score.overall-b.score.overall);$('strengths').innerHTML=insights(valid,true);$('fixes').innerHTML=insights(valid,false);$('next').innerHTML=ranked.slice(0,3).map((a,i)=>`<div class="practice"><strong>0${i+1}</strong><div><b>${esc(a.question)}</b><span>${esc(chooseFollowUp(a.question,a.score))}</span></div></div>`).join('')||'<div class="practice"><strong>—</strong><div><b>Capture a few spoken answers first.</b><span>Your next report will become more diagnostic.</span></div></div>';show('report');$('status').textContent='Complete'}
function insights(valid,good){if(!valid.length)return `<div class="insight ${good?'good':'fix'}"><b>${good?'Baseline':'Start here'}</b><span>Complete spoken answers to unlock dimension-specific coaching.</span></div>`;const dims=['relevance','knowledge','structure','specificity','communication','completeness'];const labels={relevance:'Relevant answers',knowledge:'Subject knowledge',structure:'Answer structure',specificity:'Specific examples',communication:'Delivery',completeness:'Completeness'};const avg=k=>Math.round(valid.reduce((s,a)=>s+a.score.dimensions[k],0)/valid.length);const ordered=[...dims].sort((a,b)=>good?avg(b)-avg(a):avg(a)-avg(b)).slice(0,3);return ordered.map(k=>`<div class="insight ${good?'good':'fix'}"><b>${labels[k]} · ${avg(k)}/100</b><span>${good?'This dimension is currently one of your stronger signals. Keep it consistent.':coach(k)}</span></div>`).join('')}
function coach(k){return {knowledge:'Use correct terminology, then demonstrate it with a practical school example.',structure:'Use Point → Example → Impact → Close so the panel can follow your reasoning.',specificity:'Replace generic claims with a concrete situation, action and result.',relevance:'Answer the exact question first; avoid long context before your main point.',communication:'Slow slightly, pause between ideas and finish sentences cleanly.',completeness:'Before stopping, check whether the question has multiple parts and cover each one.'}[k]}
function retryWeak(){const last=JSON.parse(localStorage.getItem(storageKey)||'null');if(!last||!last.answers)return start();const weak=last.answers.slice().sort((a,b)=>a.score.overall-b.score.overall).slice(0,3).map(a=>a.question);const all=PROFILES[role].questions;const picked=all.filter(q=>weak.includes(q[0]));if(picked.length)PROFILES[role].questions=[...picked,...all.filter(q=>!weak.includes(q[0]))];show('setup');setup()}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
setup();
