import {PROFILES,MODES} from './profiles.js';
import {scoreAnswer,chooseFollowUp,readiness} from './engine.js';
let role='librarian',mode='realistic',index=0,answers=[],stream=null,recognition=null,listening=false,started=0,timer=null,currentText='';
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function setup(){ $('roles').innerHTML=Object.entries(PROFILES).map(([k,p])=>`<button class="option ${k===role?'selected':''}" data-role="${k}"><b>${p.name}</b><span>${p.subtitle}</span></button>`).join(''); $('modes').innerHTML=Object.entries(MODES).map(([k,p])=>`<button class="option ${k===mode?'selected':''}" data-mode="${k}"><b>${p.name}</b><span>${p.desc}</span></button>`).join('');document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;setup()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;setup()});$('start').onclick=start;$('reset').onclick=reset;$('repeat').onclick=()=>say($('question').textContent);$('answer').onclick=()=>listening?stopAnswer():startAnswer();$('retry').onclick=()=>{index=0;answers=[];show('live');ask()};$('export').onclick=exportReport)}
async function start(){index=0;answers=[];$('roleTitle').textContent=PROFILES[role].name;$('modeTitle').textContent=MODES[mode].name;show('live');$('status').textContent='Live';try{stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});$('video').srcObject=stream;$('cameraMsg').style.display='none';$('face').textContent='Active'}catch{$('face').textContent='Unavailable'}ask()}
function reset(){stopMedia();if(timer)clearInterval(timer);show('setup');$('status').textContent='Ready';setup()} function stopMedia(){if(stream)stream.getTracks().forEach(t=>t.stop());if(recognition)try{recognition.stop()}catch{}listening=false}
function say(t){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.92;speechSynthesis.speak(u)}
function ask(){const q=PROFILES[role].questions;if(index>=q.length)return finish();$('counter').textContent=`Question ${index+1} / ${q.length}`;$('bar').style.width=`${index/q.length*100}%`;$('question').textContent=q[index][0];$('transcript').textContent='Press “Start answering” and speak naturally.';$('hint').textContent=mode==='pressure'?'Answer directly. Lead with your decision, then justify it.':'Pause. Structure your answer. Give evidence.';say(q[index][0])}
function startAnswer(){currentText='';if(!('SpeechRecognition'in window||'webkitSpeechRecognition'in window)){listening=true;started=Date.now();$('answer').textContent='Finish answer';$('transcript').textContent='Speech recognition is unavailable. Speak your answer, then finish.';startTimer();return}const C=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new C();recognition.lang='en-IN';recognition.continuous=true;recognition.interimResults=true;listening=true;started=Date.now();$('speech').textContent='Listening';$('answer').textContent='Stop answering';startTimer();recognition.onresult=e=>{let final=currentText,interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?final+=` ${t}`:interim+=t}currentText=final.trim();$('transcript').textContent=(currentText+' '+interim).trim()||'Listening…'};recognition.onend=()=>{if(listening)try{recognition.start()}catch{}};recognition.start()}
function startTimer(){timer=setInterval(()=>$('timer').textContent=fmt(Date.now()-started),250)} function stopAnswer(){listening=false;if(recognition)try{recognition.stop()}catch{}if(timer)clearInterval(timer);const text=currentText||$('transcript').textContent;const q=PROFILES[role].questions[index];answers.push({question:q[0],text,duration:(Date.now()-started)/1000,score:scoreAnswer(text,q[0],q[1],(Date.now()-started)/1000)});$('speech').textContent='Captured';$('timer').textContent='00:00';$('answer').textContent='Start answering';index++;setTimeout(ask,450)} function fmt(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function finish(){stopMedia();const total=readiness(answers.map(a=>a.score));const report={role,mode,total,answers,createdAt:new Date().toISOString()};localStorage.setItem('interview-os-last',JSON.stringify(report));$('overall').textContent=total;$('headline').textContent=total>=85?'Strong interview readiness.':total>=70?'Good foundation — sharpen your delivery.':'Clear improvement path identified.';$('reportMeta').textContent=`${PROFILES[role].name} · ${answers.length} questions · ${MODES[mode].name} mode`;const dims=['relevance','knowledge','structure','specificity','communication','completeness'];$('scores').innerHTML=dims.map(k=>{const v=Math.round(answers.reduce((s,a)=>s+a.score.dimensions[k],0)/Math.max(1,answers.length));return `<div class="score"><div class="scoreline"><span>${k}</span><b>${v}/100</b></div><div class="bar"><i style="width:${v}%"></i></div></div>`}).join('');const ranked=[...answers].sort((a,b)=>b.score.overall-a.score.overall);$('strengths').innerHTML=ranked.slice(0,2).map(a=>`<div class="insight good"><b>${a.score.overall}/100 · ${a.question}</b><span>${a.score.wordCount} words captured. Keep this level of substance.</span></div>`).join('');const weak=[...answers].sort((a,b)=>a.score.overall-b.score.overall);$('fixes').innerHTML=weak.slice(0,3).map(a=>`<div class="insight fix"><b>${a.score.overall}/100 · ${a.question}</b><span>${chooseFollowUp(a.question,a.score)}</span></div>`).join('');$('next').innerHTML=weak.slice(0,3).map((a,i)=>`<div class="practice"><strong>0${i+1}</strong><div><b>${a.question}</b><span>Retry with the suggested follow-up.</span></div></div>`).join('');show('report');$('status').textContent='Complete')}
function exportReport(){const raw=localStorage.getItem('interview-os-last');if(!raw)return;const blob=new Blob([raw],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`interview-os-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)} setup();
