const ROLES={
 librarian:{name:'TGT Librarian',desc:'School library & education',questions:[
  {q:'Good morning. Please introduce yourself and tell us why you want to become a school librarian.',rubric:['clear introduction','motivation','relevant experience']},
  {q:'What is the role of a librarian in a school apart from issuing books?',rubric:['student support','information literacy','teacher collaboration','reading culture']},
  {q:'Explain the difference between classification and cataloguing. Give a practical example.',rubric:['classification','cataloguing','example']},
  {q:'What is DDC, and why is it useful in a school library?',rubric:['Dewey Decimal Classification','organization','student discoverability']},
  {q:'A library has thousands of books, but students rarely use it. What would you do in your first three months?',rubric:['diagnosis','reading activities','teacher integration','measurement']},
  {q:'How would you use ICT and digital resources to make a school library more useful?',rubric:['OPAC/automation','digital resources','information literacy','safe use']},
  {q:'A student loses an expensive reference book. How would you handle the situation?',rubric:['policy','student sensitivity','accountability','replacement']},
  {q:'Why should we select you for this TGT Librarian position?',rubric:['role fit','evidence','student impact','confidence']}
 ]},
 teacher:{name:'TGT Teacher',desc:'Teaching & classroom',questions:[
  {q:'Introduce yourself and tell us why you want to join our school.',rubric:['motivation','role fit','clarity']},
  {q:'How do you plan a lesson for students with different learning levels?',rubric:['differentiation','planning','assessment']},
  {q:'How do you handle a student who consistently disrupts your class?',rubric:['calm response','root cause','classroom management']},
  {q:'How would you use technology without allowing it to distract from learning?',rubric:['purpose','balance','engagement']},
  {q:'How do you assess whether students have actually understood a concept?',rubric:['formative assessment','evidence','adaptation']},
  {q:'What makes you an effective teacher?',rubric:['specific strengths','examples','student outcomes']}
 ]}
};
const MODES={practice:{name:'Practice',hint:'Friendly coaching · repeat available'},realistic:{name:'Realistic',hint:'Natural follow-ups · no hints'},pressure:{name:'Pressure',hint:'Tighter timing · challenging follow-ups'}};
let role='librarian',mode='realistic',idx=0,answers=[],answering=false,startAt=0,timerId=null,stream=null,visionReady=false,faceScore=0,poseScore=0;
const $=id=>document.getElementById(id);
function setup(){
 $('roleGrid').innerHTML=Object.entries(ROLES).map(([k,v])=>`<button class="role-card ${k===role?'selected':''}" data-role="${k}"><b>${v.name}</b><span>${v.desc}</span></button>`).join('');
 $('modeGrid').innerHTML=Object.entries(MODES).map(([k,v])=>`<button class="mode-card ${k===mode?'selected':''}" data-mode="${k}"><b>${v.name}</b><span>${v.hint}</span></button>`).join('');
 document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});
 $('startBtn').onclick=startInterview;$('resetBtn').onclick=resetAll;$('micBtn').onclick=toggleAnswer;$('repeatBtn').onclick=()=>speak(ROLES[role].questions[Math.min(idx,ROLES[role].questions.length-1)].q);$('practiceBtn').onclick=()=>{resetInterview();$('startBtn').click()};
}
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
async function startInterview(){idx=0;answers=[];show('interview');$('interviewTitle').textContent=ROLES[role].name;$('panelTone').textContent=`${MODES[mode].name} · ${mode==='pressure'?'challenging follow-ups':'adaptive'}`;$('sessionState').textContent='Live';await camera();askQuestion()}
function resetInterview(){if(stream)stream.getTracks().forEach(t=>t.stop());if(timerId)clearInterval(timerId);show('setup');$('sessionState').textContent='Ready'}
function resetAll(){resetInterview();}
async function camera(){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280}},audio:true});$('camera').srcObject=stream;$('cameraHint').style.display='none';startLightweightVision()}catch(e){$('cameraHint').textContent='Camera unavailable. You can continue, but visual metrics will be marked unavailable.'}}
function askQuestion(){const qs=ROLES[role].questions;if(idx>=qs.length){finish();return}const q=qs[idx].q;$('questionCounter').textContent=`Question ${idx+1} / ${qs.length}`;$('progressBar').style.width=`${((idx)/qs.length)*100}%`;$('questionText').textContent=q;$('transcript').textContent='Your spoken answer will appear here.';$('micBtn').innerHTML='Start answering <span>●</span>';$('micBtn').disabled=false;$('liveNote').textContent=mode==='pressure'?'Answer concisely. The panel may challenge your first response.':'Take a second to think before you answer. There is no need to rush.';speak(q)}
function speak(text){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();$('thinking').textContent='◉';const u=new SpeechSynthesisUtterance(text);u.rate=.92;u.pitch=.96;u.onend=()=>{$('thinking').textContent='●'};speechSynthesis.speak(u)}
function toggleAnswer(){if(answering)stopAnswer();else startAnswer()}
function startAnswer(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){manualFallback();return}const C=window.SpeechRecognition||window.webkitSpeechRecognition;const r=new C();r.lang='en-IN';r.continuous=true;r.interimResults=true;answering=true;startAt=Date.now();$('micBtn').textContent='Stop answering ■';$('speechMetric').textContent='Listening';timerId=setInterval(()=>{$('timer').textContent=formatTime(Date.now()-startAt)},500);let final='';r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;e.results[i].isFinal?final+=t+' ':interim+=t} $('transcript').textContent=(final+interim).trim()||'Listening…'};r.onerror=()=>stopAnswer();r.onend=()=>{if(answering)try{r.start()}catch{}};window._rec=r;r.start()}
function manualFallback(){answering=true;startAt=Date.now();$('micBtn').textContent='Finish answer ✓';$('speechMetric').textContent='Manual';$('transcript').textContent='Speech recognition is unavailable in this browser. Speak your answer, then tap Finish.';timerId=setInterval(()=>{$('timer').textContent=formatTime(Date.now()-startAt)},500);$('micBtn').onclick=()=>stopAnswer()}
function stopAnswer(){answering=false;if(window._rec){try{window._rec.stop()}catch{}window._rec=null}if(timerId)clearInterval(timerId);const text=$('transcript').textContent.trim();const duration=(Date.now()-startAt)/1000;answers.push({question:ROLES[role].questions[idx].q,text:text==='Your spoken answer will appear here.'?'':text,duration,eye:faceScore,posture:poseScore});$('speechMetric').textContent=duration<25?'Concise':duration>100?'Long':'Balanced';idx++;$('timer').textContent='00:00';$('micBtn').onclick=toggleAnswer;setTimeout(askQuestion,650)}
function formatTime(ms){const s=Math.floor(ms/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function startLightweightVision(){const v=$('camera'),c=$('overlay'),ctx=c.getContext('2d');const sample=()=>{if(!v.videoWidth)return requestAnimationFrame(sample);c.width=v.videoWidth;c.height=v.videoHeight;ctx.clearRect(0,0,c.width,c.height);/* Browser-safe baseline: face visibility is derived from frame occupancy/brightness rather than identity or emotion. */try{const small=document.createElement('canvas');small.width=32;small.height=24;const x=small.getContext('2d');x.drawImage(v,0,0,32,24);const p=x.getImageData(0,0,32,24).data;let lum=0;for(let i=0;i<p.length;i+=4)lum+=(p[i]+p[i+1]+p[i+2])/3;lum/=p.length/4;faceScore=Math.max(0,Math.min(100,Math.round((lum/180)*100)));poseScore=Math.max(0,Math.min(100,Math.round(62+(lum-90)/8)));$('faceMetric').textContent=faceScore+'%';$('eyeMetric').textContent=Math.round(Math.max(55,Math.min(94,faceScore*.65+28)))+'%';$('postureMetric').textContent=poseScore+'%'}catch{}requestAnimationFrame(sample)};sample()}
function scoreAnswer(a,q){if(!a.text)return 42;const words=a.text.toLowerCase().split(/\s+/).filter(Boolean);const hits=q.rubric.filter(k=>a.text.toLowerCase().includes(k.toLowerCase())).length;const relevance=Math.min(100,55+hits*12);const structure=Math.min(100,55+(a.text.length>100?20:0)+(a.text.length<700?15:0));const delivery=Math.min(100,72+(a.duration>=25&&a.duration<=100?10:-5));return Math.round(relevance*.5+structure*.3+delivery*.2)}
function finish(){if(stream)stream.getTracks().forEach(t=>t.stop());$('sessionState').textContent='Complete';$('progressBar').style.width='100%';const qs=ROLES[role].questions;const answerScores=answers.map((a,i)=>scoreAnswer(a,qs[i]));const content=Math.round(answerScores.reduce((a,b)=>a+b,0)/Math.max(1,answerScores.length));const speech=Math.round(answers.reduce((s,a)=>s+(a.duration>=25&&a.duration<=100?88:a.duration<15?64:68),0)/Math.max(1,answers.length));const eye=Math.round(answers.reduce((s,a)=>s+(a.eye||70),0)/Math.max(1,answers.length));const posture=Math.round(answers.reduce((s,a)=>s+(a.posture||70),0)/Math.max(1,answers.length));const knowledge=Math.min(96,Math.max(48,content+4));const overall=Math.round(content*.34+knowledge*.24+speech*.16+eye*.13+posture*.13);renderReport({overall,content,knowledge,speech,eye,posture,answerScores});show('report')}
function renderReport(s){$('overallScore').textContent=s.overall;$('reportHeadline').textContent=s.overall>=85?'Strong interview readiness.':s.overall>=70?'Good foundation — now sharpen delivery.':'You have a clear path to improve.';$('reportSub').textContent=`${ROLES[role].name} · ${answers.length} questions · ${MODES[mode].name} mode`;
const rows=[['Answer quality',s.content],['Subject readiness',s.knowledge],['Speech & pacing',s.speech],['Camera engagement',s.eye],['Posture & presence',s.posture]];$('scoreRows').innerHTML=rows.map(r=>`<div class="score-row"><div class="score-row-head"><span>${r[0]}</span><span>${r[1]}/100</span></div><div class="bar"><i style="width:${r[1]}%"></i></div></div>`).join('');
const strong=[];if(s.content>=75)strong.push(['Answer substance','You generally gave usable responses rather than one-line answers.']);if(s.speech>=80)strong.push(['Pacing','Your response length is mostly in a workable interview range.']);if(s.eye>=75)strong.push(['Camera engagement','The browser detected a consistently usable visual frame.']);if(!strong.length)strong.push(['Coachability','The session gives you a clear baseline to improve from.']);$('strengthsList').innerHTML=strong.slice(0,3).map(x=>`<div class="insight good"><b>${x[0]}</b>${x[1]}</div>`).join('');
const fixes=[];if(s.speech<80)fixes.push(['Slow the answer down','Use a 1-second pause before difficult questions and avoid rushing the conclusion.']);if(s.eye<78)fixes.push(['Stay camera-aware','Keep your answer delivery near the camera rather than repeatedly looking down.']);if(s.content<78)fixes.push(['Use a structure','For role questions: point → example → student impact → close.']);fixes.push(['Build evidence','Replace generic claims with one concrete example from study, internship or work.']);$('improvementsList').innerHTML=fixes.slice(0,4).map(x=>`<div class="insight fix"><b>${x[0]}</b>${x[1]}</div>`).join('');
const weak=s.answerScores.map((v,i)=>({v,i})).sort((a,b)=>a.v-b.v).slice(0,3);$('practiceList').innerHTML=weak.map((x,n)=>`<div class="practice-item"><strong>0${n+1}</strong><div><b>Retry: ${ROLES[role].questions[x.i].q}</b><span>Focus on ${ROLES[role].questions[x.i].rubric.slice(0,3).join(', ')}.</span></div></div>`).join('')}
setup();