"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, Database, KeyRound, Languages, Save, ShieldCheck, SlidersHorizontal } from "lucide-react";
const KEY="solprovo.settings.v1";
export default function SettingsPage(){
 const [language,setLanguage]=useState("Hinglish"),[vertical,setVertical]=useState("Real Estate"),[saved,setSaved]=useState(false);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");if(x.language)setLanguage(x.language);if(x.vertical)setVertical(x.vertical)}catch{}},[]);
 function save(){localStorage.setItem(KEY,JSON.stringify({language,vertical,updatedAt:new Date().toISOString()}));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 return <main className="content" style={{maxWidth:1120,margin:"0 auto"}}>
  <div className="header"><div><Link href="/" className="btn" style={{textDecoration:"none",display:"inline-block",marginBottom:14}}><ArrowLeft size={14} style={{verticalAlign:"-2px",marginRight:6}}/>ProspectOS</Link><h1>Workspace Settings</h1><p className="sub">Preferences now persist in the workspace and provide defaults for future automation.</p></div></div>
  <div className="grid2"><div className="card panel"><div className="panel-head"><h2>Sales defaults</h2><SlidersHorizontal size={16} color="var(--muted)"/></div><label className="panel-note">Primary vertical</label><select className="select" style={{width:"100%",marginTop:6}} value={vertical} onChange={e=>setVertical(e.target.value)}><option>Real Estate</option><option>Dental Clinic</option><option>Local Retail</option><option>Other Local Business</option></select><label className="panel-note" style={{display:"block",marginTop:16}}>Preferred customer language</label><select className="select" style={{width:"100%",marginTop:6}} value={language} onChange={e=>setLanguage(e.target.value)}><option>Hindi</option><option>English</option><option>Hinglish</option></select><div style={{marginTop:18,padding:12,borderRadius:9,background:"var(--blue-soft)",fontSize:11,color:"var(--muted)"}}><Languages size={13} style={{verticalAlign:"-2px",marginRight:6}}/>Future messaging and voice modules will use this preference as their starting point.</div><button className="btn primary" style={{marginTop:16}} onClick={save}><Save size={14} style={{verticalAlign:"-2px",marginRight:5}}/>{saved?"Saved":"Save preferences"}</button></div>
   <div className="card panel"><div className="panel-head"><h2>Integrations</h2><Database size={16} color="var(--muted)"/></div><Integration name="Google Places" detail="Business discovery" status="Configured"/><Integration name="Website Analyzer" detail="Public website audit" status="Ready"/><Integration name="Workspace data" detail="Shared browser persistence foundation" status="Ready"/><Integration name="Firebase" detail="Cloud persistence + auth" status="Build next"/><Integration name="WhatsApp" detail="Customer messaging" status="Build next"/><Integration name="Voice" detail="Hindi + English calling" status="Build next"/><div style={{marginTop:16,padding:12,borderRadius:9,background:"var(--amber-soft)",color:"var(--amber)",fontSize:10,lineHeight:1.5}}><KeyRound size={13} style={{verticalAlign:"-2px",marginRight:5}}/><strong>Secrets stay server-side.</strong> API keys belong in deployment secrets, never in client components or Git.</div></div></div>
  <div className="card panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Trust & acquisition policy</h2><div className="panel-note">Hard rules for the product.</div></div><ShieldCheck size={16} color="var(--green)"/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[["Evidence first","No verified evidence → no hard claim."],["Human control","Automation suggests and routes; owners approve or override."],["Consent aware","No indiscriminate bulk calling or messaging."],["India first","Hindi, English and Hinglish are first-class modes."],["Outcome focused","Sell leads, appointments and follow-up — not AI."],["Transparent","Customers can see what the system did and why."]].map(([a,b])=><div key={a} style={{padding:14,border:"1px solid var(--line)",borderRadius:10}}><strong style={{fontSize:12}}>{a}</strong><p className="panel-note" style={{marginTop:5,lineHeight:1.5}}>{b}</p></div>)}</div></div>
 </main>
}
function Integration({name,detail,status}:{name:string;detail:string;status:string}){const live=status==="Configured"||status==="Ready";return <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,padding:"12px 0",borderBottom:"1px solid var(--line)"}}><div><strong style={{fontSize:12}}>{name}</strong><div className="panel-note">{detail}</div></div><span className={`badge ${live?"hot":"muted"}`}>{live?<CheckCircle2 size={11} style={{verticalAlign:"-2px",marginRight:4}}/>:null}{status}</span></div>}
