"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ExternalLink, FileSearch, Loader2, MapPinned, Search, ShieldCheck, TriangleAlert, XCircle, BookmarkPlus, Check, BookmarkMinus, Sparkles } from "lucide-react";
import { loadProspects, removeProspect, upsertProspect, type WorkspaceProspect } from "@/lib/workspace";
import { buildProspectIntelligence } from "@/lib/intelligence";

type Place = { placeId:string|null; name:string; address:string|null; website:string|null; mapsUrl:string|null; types:string[]; businessStatus:string|null; source:string };
type AuditResult = { url:string; title:string; score:number; opportunities:number; status:"ready"|"error"; message:string };
const SOCIAL_HOSTS=new Set(["instagram.com","www.instagram.com","facebook.com","www.facebook.com","linkedin.com","www.linkedin.com","youtube.com","www.youtube.com","x.com","www.x.com","twitter.com","www.twitter.com"]);
function getHost(value:string){try{return new URL(value).hostname.toLowerCase()}catch{return ""}}
function isSocialUrl(value:string){const host=getHost(value);return SOCIAL_HOSTS.has(host)||host.endsWith(".instagram.com")||host.endsWith(".facebook.com")||host.endsWith(".linkedin.com")||host.endsWith(".youtube.com")}
function isAuditableWebsite(value:string){return Boolean(value)&&!isSocialUrl(value)}
function placeKey(p:Place){return p.placeId||`manual:${p.name}`}
function isSavedPlace(p:Place, savedProspects:WorkspaceProspect[]){const key=placeKey(p);return savedProspects.some(x=>x.id===key || (!!p.website && x.website===p.website));}

export default function DiscoveryPage(){
 const [category,setCategory]=useState("real estate agents"),[location,setLocation]=useState("Greater Noida"),[limit,setLimit]=useState("10"),[places,setPlaces]=useState<Place[]>([]),[audits,setAudits]=useState<AuditResult[]>([]),[loading,setLoading]=useState(false),[auditing,setAuditing]=useState(false),[error,setError]=useState(""),[savedProspects,setSavedProspects]=useState<WorkspaceProspect[]>(()=>loadProspects());
 const websites=useMemo(()=>places.filter(p=>p.website&&isAuditableWebsite(p.website)&&!isSavedPlace(p,savedProspects)).map(p=>p.website as string),[places,savedProspects]);
 const socialProfiles=useMemo(()=>places.filter(p=>p.website&&isSocialUrl(p.website)),[places]);
 const availablePlaces=useMemo(()=>places.filter(p=>!isSavedPlace(p,savedProspects)),[places,savedProspects]);
 const savedFromSearch=useMemo(()=>places.filter(p=>isSavedPlace(p,savedProspects)),[places,savedProspects]);
 async function discover(){setLoading(true);setError("");setPlaces([]);setAudits([]);try{const r=await fetch("/api/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,location,limit:Number(limit)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Discovery failed.");setPlaces(d.places||[])}catch(e){setError(e instanceof Error?e.message:"Discovery failed")}finally{setLoading(false)}}
 async function auditDiscovered(){if(!websites.length)return;setAuditing(true);setError("");setAudits([]);const next:AuditResult[]=[];for(const url of websites.slice(0,10)){try{const r=await fetch("/api/audit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url,businessName:places.find(p=>p.website===url)?.name||category})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Audit failed.");const a=d.audit||d;next.push({url,title:a.title||"Untitled website",score:Number(a.score)||0,opportunities:Array.isArray(a.opportunities)?a.opportunities.length:0,status:"ready",message:"Evidence collected"})}catch(e){next.push({url,title:"Could not analyze",score:0,opportunities:0,status:"error",message:e instanceof Error?e.message:"Audit failed"})}}setAudits(next);setAuditing(false)}
 function savePlace(p:Place,audit?:AuditResult){const score=audit?.score||0;const intel=buildProspectIntelligence({category:p.types?.join(" ")||category,score,gaps:audit?.opportunities||0});upsertProspect({id:placeKey(p),name:p.name,category:p.types?.[0]||category,location:addressToLocation(p.address,location),website:p.website||undefined,mapsUrl:p.mapsUrl||undefined,score,gaps:audit?.opportunities||0,stage:"New",nextAction:intel.nextBestAction,createdAt:new Date().toISOString(),source:"Google Places",opportunityLabel:intel.opportunityLabel,opportunityReason:intel.reason,recommendedService:intel.recommendedService,recommendedPackage:intel.recommendedPackage,demoType:intel.demoType});setSavedProspects(loadProspects())}
 function unsave(p:Place){removeProspect(placeKey(p));setSavedProspects(loadProspects())}
 function saveAndDemo(p:Place,audit?:AuditResult){savePlace(p,audit);const id=placeKey(p);window.location.href=`/demo?prospect=${encodeURIComponent(id)}`}
 return <main className="content" style={{maxWidth:1240,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:28}}><Link href="/" className="btn" style={{textDecoration:"none"}}><ArrowLeft size={14} style={{verticalAlign:"-2px",marginRight:6}}/>ProspectOS</Link><span className="badge muted"><ShieldCheck size={12} style={{verticalAlign:"-2px",marginRight:4}}/>Evidence-first discovery</span></div>
  <div className="card panel" style={{marginBottom:18}}><div style={{display:"flex",gap:12,alignItems:"center",marginBottom:8}}><MapPinned size={20} color="var(--blue)"/><h1>Live Business Discovery</h1></div><p className="sub">Find real businesses through Google Places, audit their public websites, then save qualified prospects into the shared SolProvo workspace.</p><div style={{display:"grid",gridTemplateColumns:"1.2fr 1fr .35fr auto",gap:12,marginTop:22,alignItems:"end"}}><div><label className="panel-note">Business category</label><input className="search" style={{width:"100%",marginTop:6}} value={category} onChange={e=>setCategory(e.target.value)} placeholder="real estate agents"/></div><div><label className="panel-note">Target market</label><input className="search" style={{width:"100%",marginTop:6}} value={location} onChange={e=>setLocation(e.target.value)} placeholder="Greater Noida"/></div><div><label className="panel-note">Results</label><select className="select" style={{width:"100%",marginTop:6}} value={limit} onChange={e=>setLimit(e.target.value)}><option>5</option><option>10</option><option>20</option></select></div><button className="btn primary" disabled={loading||!category.trim()||!location.trim()} onClick={discover}>{loading?<><Loader2 size={14} className="spin" style={{verticalAlign:"-2px",marginRight:6}}/>Finding…</>:<><Search size={14} style={{verticalAlign:"-2px",marginRight:6}}/>Find businesses</>}</button></div>{error&&<div style={{marginTop:14,padding:12,borderRadius:10,background:"var(--red-soft)",color:"var(--red)",fontSize:12}}><TriangleAlert size={13} style={{verticalAlign:"-2px",marginRight:5}}/>{error}</div>}</div>
  {places.length>0&&<section className="card panel" style={{marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:14}}><div><strong>Live prospects found</strong><div className="panel-note">{availablePlaces.length} new businesses · {savedFromSearch.length} already saved · {websites.length} auditable new websites.</div></div><button className="btn primary" disabled={auditing||!websites.length} onClick={auditDiscovered}>{auditing?<><Loader2 size={14} className="spin" style={{verticalAlign:"-2px",marginRight:6}}/>Auditing websites…</>:<><FileSearch size={14} style={{verticalAlign:"-2px",marginRight:6}}/>Audit {websites.length} websites</>}</button></div>
   {availablePlaces.length>0?<div className="card table"><table><thead><tr><th>Business</th><th>Address</th><th>Website</th><th>Maps</th><th>Source</th><th>Actions</th></tr></thead><tbody>{availablePlaces.map(p=>{const audit=audits.find(a=>a.url===p.website);return <tr key={placeKey(p)}><td><div className="business"><div className="business-icon"><MapPinned size={15}/></div><div><div className="business-name">{p.name}</div><div className="business-meta">{p.businessStatus||"Status not supplied"}</div></div></div></td><td>{p.address||"—"}</td><td>{p.website?<div><a className="link-btn" href={p.website} target="_blank" rel="noreferrer">{isSocialUrl(p.website)?"Social profile":"Website"} <ExternalLink size={11}/></a>{isSocialUrl(p.website)&&<div className="business-meta">Not audited as a website</div>}</div>:<span className="panel-note">No website returned</span>}</td><td>{p.mapsUrl?<a className="link-btn" href={p.mapsUrl} target="_blank" rel="noreferrer">Maps <ExternalLink size={11}/></a>:"—"}</td><td><span className="badge muted">Places API</span></td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="btn" onClick={()=>savePlace(p,audit)}><BookmarkPlus size={13} style={{verticalAlign:"-2px",marginRight:4}}/>Save</button>{audit?.status==="ready"&&<button className="btn primary" onClick={()=>saveAndDemo(p,audit)}><Sparkles size={13} style={{verticalAlign:"-2px",marginRight:4}}/>Create demo</button>}</div></td></tr>})}</tbody></table></div>:<div className="panel-note" style={{padding:16}}>All returned businesses are already saved in your workspace.</div>}
   {savedFromSearch.length>0&&<div style={{marginTop:14}}><div style={{fontSize:12,fontWeight:800,marginBottom:8}}>Already saved from this search</div><div className="card table"><table><thead><tr><th>Business</th><th>Stage</th><th>Website</th><th></th></tr></thead><tbody>{savedFromSearch.map(p=>{const savedItem=savedProspects.find(x=>x.id===placeKey(p)||x.website===p.website);return <tr key={`saved-${placeKey(p)}`}><td><strong>{p.name}</strong><div className="business-meta">{p.category||category} · {savedItem?.location||location}</div></td><td><span className="badge muted">{savedItem?.stage||"Saved"}</span></td><td>{p.website?<a className="link-btn" href={p.website} target="_blank" rel="noreferrer">Website <ExternalLink size={11}/></a>:"—"}</td><td><button className="btn" onClick={()=>unsave(p)}><BookmarkMinus size={13} style={{verticalAlign:"-2px",marginRight:4}}/>Unsave</button></td></tr>})}</tbody></table></div></div>}
   <p className="panel-note" style={{marginTop:12}}>{socialProfiles.length?`${socialProfiles.length} social profile${socialProfiles.length===1?"":"s"} excluded from website auditing. `:""}Google Maps/Places is discovery evidence, not a scraped contact database.</p></section>}
  {audits.length>0&&<section className="card table" style={{marginBottom:18}}><div className="panel" style={{paddingBottom:8}}><strong>Evidence-backed opportunity queue</strong><div className="panel-note">Each ready lead can now be saved and opened directly in Demo Factory.</div></div><table><thead><tr><th>Website</th><th>Opportunity</th><th>Gaps</th><th>Evidence</th><th>Action</th></tr></thead><tbody>{audits.map(r=>{const place=places.find(p=>p.website===r.url);const intel=buildProspectIntelligence({category:place?.types?.join(" ")||category,score:r.score,gaps:r.opportunities});const savedItem=place?loadProspects().find(x=>x.id===placeKey(place)||x.website===place.website):undefined;return <tr key={r.url}><td><div className="business"><div className="business-icon"><FileSearch size={15}/></div><div><div className="business-name">{r.title}</div><div className="business-meta">{r.url}</div></div></div></td><td>{r.status==="ready"?<div><span className={`score ${r.score>=70?"high":r.score>=33?"medium":"low"}`}>{r.score}/100</span><div className="business-meta">{intel.opportunityLabel} opportunity</div></div>:"—"}</td><td>{r.status==="ready"?<span className={r.opportunities?"badge hot":"badge muted"}>{r.opportunities} verified gaps</span>:"—"}</td><td><span className={r.status==="ready"?"badge hot":"badge warn"}>{r.status==="ready"?<><CheckCircle2 size={12} style={{marginRight:4}}/>Evidence collected</>:<><XCircle size={12} style={{marginRight:4}}/>Failed</>}</span><div className="business-meta">{r.status==="ready"?intel.recommendedService:r.message}</div></td><td>{r.status==="ready"&&place?<div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Link className="link-btn" href={`/analyze?url=${encodeURIComponent(r.url)}&from=discovery`}>Open audit</Link><button className="btn primary" onClick={()=>savedItem?window.location.href=`/demo?prospect=${encodeURIComponent(savedItem.id)}`:saveAndDemo(place,r)}><Sparkles size={13} style={{verticalAlign:"-2px",marginRight:4}}/>{savedItem?"Create demo":"Save + demo"}</button></div>:"—"}</td></tr>})}</tbody></table></section>}
  <div className="card panel" style={{background:"var(--blue-soft)"}}><strong style={{fontSize:12}}>Production rule</strong><p className="panel-note" style={{marginTop:6,lineHeight:1.5}}>Missing evidence means “not detected here”, not “the business definitely does not have it”. Social profiles and unreachable pages are never treated as proof of a website gap.</p></div>
 </main>
}
function addressToLocation(_address:string|null,fallback:string){return fallback}
