"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CheckCircle2, ExternalLink, FileSearch, Loader2, MapPinned, Search, ShieldCheck, TriangleAlert, XCircle, BookmarkPlus, BookmarkMinus, Sparkles } from "lucide-react";
import { loadProspects, removeProspect, upsertProspect, type WorkspaceProspect } from "@/lib/workspace";
import { buildProspectIntelligence } from "@/lib/intelligence";

type Place={placeId:string|null;name:string;address:string|null;website:string|null;mapsUrl:string|null;phone?:string|null;photoNames?:string[];types:string[];businessStatus:string|null;source:string};
type AuditResult={url:string;title:string;score:number;opportunities:number;images?:string[];status:"ready"|"error";message:string};
type DiscoveryState={category:string;location:string;limit:string;places:Place[];audits:AuditResult[]};
const DISCOVERY_KEY="solprovo.discovery.v2"; const SOCIAL_HOSTS=new Set(["instagram.com","www.instagram.com","facebook.com","www.facebook.com","linkedin.com","www.linkedin.com","youtube.com","www.youtube.com","x.com","www.x.com","twitter.com","www.twitter.com"]);
function getHost(v:string){try{return new URL(v).hostname.toLowerCase()}catch{return ""}} function isSocialUrl(v:string){const h=getHost(v);return SOCIAL_HOSTS.has(h)||h.endsWith(".instagram.com")||h.endsWith(".facebook.com")||h.endsWith(".linkedin.com")||h.endsWith(".youtube.com")}
function placeKey(p:Place){return p.placeId||`manual:${p.name}`} function isSavedPlace(p:Place,s:WorkspaceProspect[]){const k=placeKey(p);return s.some(x=>x.id===k||!!p.website&&x.website===p.website)}
function loadDiscoveryState():DiscoveryState|null{if(typeof window==="undefined")return null;try{const r=localStorage.getItem(DISCOVERY_KEY);return r?JSON.parse(r):null}catch{return null}} function persistDiscovery(s:DiscoveryState){if(typeof window!=="undefined")try{localStorage.setItem(DISCOVERY_KEY,JSON.stringify(s))}catch{}}
export default function DiscoveryPage(){
 const [category,setCategory]=useState("real estate agents"),[location,setLocation]=useState("Greater Noida"),[limit,setLimit]=useState("10"),[places,setPlaces]=useState<Place[]>([]),[audits,setAudits]=useState<AuditResult[]>([]),[loading,setLoading]=useState(false),[auditing,setAuditing]=useState(false),[error,setError]=useState(""),[savedProspects,setSavedProspects]=useState<WorkspaceProspect[]>(()=>loadProspects());
 useEffect(()=>{const s=loadDiscoveryState();if(s){setCategory(s.category||"real estate agents");setLocation(s.location||"Greater Noida");setLimit(s.limit||"10");setPlaces(Array.isArray(s.places)?s.places:[]);setAudits(Array.isArray(s.audits)?s.audits:[])}},[]); useEffect(()=>{if(places.length||audits.length)persistDiscovery({category,location,limit,places,audits})},[category,location,limit,places,audits]);
 const websites=useMemo(()=>places.filter(p=>p.website&&!isSocialUrl(p.website)&&!isSavedPlace(p,savedProspects)).map(p=>p.website as string),[places,savedProspects]); const availablePlaces=useMemo(()=>places.filter(p=>!isSavedPlace(p,savedProspects)),[places,savedProspects]); const savedFromSearch=useMemo(()=>places.filter(p=>isSavedPlace(p,savedProspects)),[places,savedProspects]);
 async function discover(){setLoading(true);setError("");setPlaces([]);setAudits([]);try{const r=await fetch("/api/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({category,location,limit:Number(limit)})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Discovery failed.");setPlaces(d.places||[])}catch(e){setError(e instanceof Error?e.message:"Discovery failed")}finally{setLoading(false)}}
 async function auditDiscovered(){if(!websites.length)return;setAuditing(true);setError("");setAudits([]);const next:AuditResult[]=[];for(const url of websites.slice(0,10)){try{const r=await fetch("/api/audit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({url,businessName:places.find(p=>p.website===url)?.name||category})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Audit failed.");const a=d.audit||d;next.push({url,title:a.title||"Untitled website",score:Number(a.score)||0,opportunities:Array.isArray(a.opportunities)?a.opportunities.length:0,images:Array.isArray(a.images)?a.images:[],status:"ready",message:"Evidence collected"})}catch(e){next.push({url,title:"Could not analyze",score:0,opportunities:0,status:"error",message:e instanceof Error?e.message:"Audit failed"})}}setAudits(next);setAuditing(false)}
 function savePlace(p:Place,audit?:AuditResult){const score=audit?.score||0;const intel=buildProspectIntelligence({category:p.types?.join(" ")||category,score,gaps:audit?.opportunities||0,websitePresent:Boolean(p.website&&!isSocialUrl(p.website))});upsertProspect({id:placeKey(p),name:p.name,category:p.types?.[0]||category,location:p.address||location,website:p.website||undefined,mapsUrl:p.mapsUrl||undefined,phone:p.phone||undefined,imageUrls:audit?.images||[],mapsPhotoNames:p.photoNames||[],score,gaps:audit?.opportunities||0,stage:"New",nextAction:intel.nextBestAction,createdAt:new Date().toISOString(),source:"Google Places",opportunityLabel:intel.opportunityLabel,opportunityReason:intel.reason,recommendedService:intel.recommendedService,recommendedPackage:intel.recommendedPackage,demoType:intel.demoType});setSavedProspects(loadProspects())}
 function unsave(p:Place){removeProspect(placeKey(p));setSavedProspects(loadProspects())} function saveAndDemo(p:Place,a?:AuditResult){savePlace(p,a);window.location.href=`/demo?prospect=${encodeURIComponent(placeKey(p))}&from=discovery`}
 return <main className="content" style={{maxWidth:1240,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:28}}><Link href="/" className="btn"><ArrowLeft size={14}/> ProspectOS</Link><span className="badge muted"><ShieldCheck size={12}/> Evidence-first discovery</span></div>
  <div className="card panel" style={{marginBottom:18}}><div style={{display:"flex",gap:12,alignItems:"center",marginBottom:8}}><MapPinned size={20} color="var(--blue)"/><h1>Live Business Discovery</h1></div><p className="sub">Find businesses through Google Places, keep every result — including businesses without websites — then build a polished website/system demo from verified Maps and public-web context.</p><div style={{display:"grid",gridTemplateColumns:"1.2fr 1fr .35fr auto",gap:12,marginTop:22,alignItems:"end"}}><div><label className="panel-note">Business category</label><input className="search" style={{width:"100%",marginTop:6}} value={category} onChange={e=>setCategory(e.target.value)}/></div><div><label className="panel-note">Target market</label><input className="search" style={{width:"100%",marginTop:6}} value={location} onChange={e=>setLocation(e.target.value)}/></div><div><label className="panel-note">Results</label><select className="select" style={{width:"100%",marginTop:6}} value={limit} onChange={e=>setLimit(e.target.value)}><option>5</option><option>10</option><option>20</option></select></div><button className="btn primary" disabled={loading||!category.trim()||!location.trim()} onClick={discover}>{loading?<><Loader2 size={14} className="spin"/> Finding…</>:<><Search size={14}/> Find businesses</>}</button></div>{error&&<div style={{marginTop:14,padding:12,borderRadius:10,background:"var(--red-soft)",color:"var(--red)",fontSize:12}}><TriangleAlert size={13}/> {error}</div>}</div>
  {places.length>0&&<section className="card panel" style={{marginBottom:18}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:14}}><div><strong>Live prospects found</strong><div className="panel-note">{availablePlaces.length} new · {savedFromSearch.length} saved · {websites.length} auditable websites. No-website businesses remain first-class opportunities.</div></div><button className="btn primary" disabled={auditing||!websites.length} onClick={auditDiscovered}>{auditing?<><Loader2 size={14} className="spin"/> Auditing…</>:<><FileSearch size={14}/> Audit {websites.length} websites</>}</button></div>
   {availablePlaces.length>0?<div className="card table"><table><thead><tr><th>Business</th><th>Address</th><th>Website / presence</th><th>Maps</th><th>Contact</th><th>Actions</th></tr></thead><tbody>{availablePlaces.map(p=>{const a=audits.find(x=>x.url===p.website);return <tr key={placeKey(p)}><td><div className="business"><div className="business-icon"><MapPinned size={15}/></div><div><div className="business-name">{p.name}</div><div className="business-meta">{p.businessStatus||"Status not supplied"} · {p.types?.[0]||category}</div></div></div></td><td>{p.address||"—"}</td><td>{p.website?<a className="link-btn" href={p.website} target="_blank" rel="noreferrer">{isSocialUrl(p.website)?"Social profile":"Website"} <ExternalLink size={11}/></a>:<div><span className="badge hot">No website</span><div className="business-meta">Build from Maps context</div></div>}</td><td>{p.mapsUrl?<a className="link-btn" href={p.mapsUrl} target="_blank" rel="noreferrer">Open Maps <ExternalLink size={11}/></a>:"—"}</td><td>{p.phone||<span className="panel-note">No phone returned</span>}</td><td><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button className="btn" onClick={()=>savePlace(p,a)}><BookmarkPlus size={13}/> Save</button><button className="btn primary" onClick={()=>saveAndDemo(p,a)}><Sparkles size={13}/> Create website demo</button></div></td></tr>})}</tbody></table></div>:<div className="panel-note" style={{padding:16}}>All returned businesses are already saved in your workspace.</div>}
   {savedFromSearch.length>0&&<div style={{marginTop:14}}><strong style={{fontSize:12}}>Already saved from this search</strong><div className="card table" style={{marginTop:8}}><table><tbody>{savedFromSearch.map(p=>{const s=savedProspects.find(x=>x.id===placeKey(p)||x.website===p.website);return <tr key={`saved-${placeKey(p)}`}><td><strong>{p.name}</strong><div className="business-meta">{p.category||category} · {s?.location||location}</div></td><td><span className="badge muted">{s?.stage||"Saved"}</span></td><td>{p.website?"Website":"No website"}</td><td><button className="btn" onClick={()=>unsave(p)}><BookmarkMinus size={13}/> Unsave</button></td></tr>})}</tbody></table></div></div>}
   <p className="panel-note" style={{marginTop:12}}>Maps-only businesses are deliberately retained because their listing, photos and contact context can seed a new website demo.</p></section>}
  {audits.length>0&&<section className="card table" style={{marginBottom:18}}><div className="panel"><strong>Evidence-backed website opportunity queue</strong><div className="panel-note">Website images are collected from the public page when available and carried into the saved demo.</div></div><table><thead><tr><th>Website</th><th>Opportunity</th><th>Gaps</th><th>Evidence</th><th>Action</th></tr></thead><tbody>{audits.map(r=>{const p=places.find(x=>x.website===r.url);const intel=buildProspectIntelligence({category:p?.types?.join(" ")||category,score:r.score,gaps:r.opportunities});const saved=p?loadProspects().find(x=>x.id===placeKey(p)||x.website===p.website):undefined;return <tr key={r.url}><td><div className="business"><div className="business-icon"><FileSearch size={15}/></div><div><div className="business-name">{r.title}</div><div className="business-meta">{r.url} · {r.images?.length||0} images</div></div></div></td><td>{r.status==="ready"?<><span className={`score ${r.score>=70?"high":r.score>=33?"medium":"low"}`}>{r.score}/100</span><div className="business-meta">{intel.opportunityLabel}</div></>:"—"}</td><td>{r.status==="ready"?<span className={r.opportunities?"badge hot":"badge muted"}>{r.opportunities} verified gaps</span>:"—"}</td><td><span className={r.status==="ready"?"badge hot":"badge warn"}>{r.status==="ready"?<><CheckCircle2 size={12}/> Evidence collected</>:<><XCircle size={12}/> Failed</>}</span></td><td>{r.status==="ready"&&p?<div style={{display:"flex",gap:6,flexWrap:"wrap"}}><Link className="link-btn" href={`/analyze?url=${encodeURIComponent(r.url)}&from=discovery`}>Open audit</Link><button className="btn primary" onClick={()=>saved?window.location.href=`/demo?prospect=${encodeURIComponent(saved.id)}&from=discovery`:saveAndDemo(p,r)}><Sparkles size={13}/> {saved?"Create demo":"Save + demo"}</button></div>:"—"}</td></tr>})}</tbody></table></section>}
  <div className="card panel" style={{background:"var(--blue-soft)"}}><strong style={{fontSize:12}}>Production rule</strong><p className="panel-note" style={{marginTop:6,lineHeight:1.5}}>Missing website evidence means “website opportunity”. Public images and Maps photos are source material, not proof of ownership, quality or business claims. Production copy and branding require owner approval.</p></div></main>
}
