"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bot, CalendarDays, CheckCircle2, ChevronRight, MessageCircle, Phone, Send, Star, Users, WalletCards } from "lucide-react";

type Module = { key:string; icon:typeof Users; title:string; description:string; status:"Build next"|"Foundation"; price:string };
const modules: Module[] = [
 {key:"leads",icon:Users,title:"Lead Inbox",description:"Capture enquiries from forms, WhatsApp, calls and campaigns into one owner-controlled queue.",status:"Foundation",price:"Starter"},
 {key:"appointments",icon:CalendarDays,title:"Appointments & Site Visits",description:"Request, confirm, reschedule and track appointments without losing the conversation history.",status:"Build next",price:"Starter"},
 {key:"offers",icon:WalletCards,title:"Offers & Campaigns",description:"Create local offers in English, Hindi or Hinglish and send them only through configured channels.",status:"Build next",price:"Growth"},
 {key:"messaging",icon:MessageCircle,title:"WhatsApp Inbox",description:"Centralize customer conversations with templates, quick replies and human handoff.",status:"Build next",price:"Growth"},
 {key:"voice",icon:Phone,title:"Calling / Voice Agent",description:"Optional Hindi + English receptionist for qualified inbound enquiries and approved follow-up flows.",status:"Build next",price:"Premium"},
 {key:"reviews",icon:Star,title:"Reviews & Reactivation",description:"Ask happy customers for reviews and bring past customers back with relevant offers.",status:"Build next",price:"Growth"},
 {key:"ai",icon:Bot,title:"AI Assistant",description:"AI stays behind the scenes: summarize leads, suggest replies and surface next actions without making the product look AI-generated.",status:"Build next",price:"Premium"},
];

export default function BusinessOSPage(){
 const [selected,setSelected]=useState("leads");
 return <main className="content" style={{maxWidth:1280,margin:"0 auto"}}>
  <div className="header"><div><Link href="/" className="btn" style={{textDecoration:"none",display:"inline-block",marginBottom:14}}><ArrowLeft size={14} style={{verticalAlign:"-2px",marginRight:6}}/>ProspectOS</Link><h1>BusinessOS</h1><p className="sub">The system we sell to Indian local businesses — simple on the surface, powerful underneath.</p></div><div className="badge hot"><CheckCircle2 size={12} style={{verticalAlign:"-2px",marginRight:4}}/>India-first roadmap</div></div>
  <div className="card panel" style={{background:"#101722",color:"#fff",marginBottom:18}}><div style={{display:"grid",gridTemplateColumns:"1.3fr 1fr",gap:24,alignItems:"center"}}><div><span style={{fontSize:10,letterSpacing:".12em",fontWeight:800,color:"#8e9aaa"}}>CUSTOMER PROMISE</span><h2 style={{fontFamily:"Manrope",fontSize:26,marginTop:8}}>“Aapka business, aapke control mein.”</h2><p style={{color:"#aeb8c6",fontSize:12,lineHeight:1.6,marginTop:8}}>One place to see leads, appointments, offers, follow-ups and customer conversations. AI assists the owner; it never takes ownership away from them.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:9}}>{["New lead","Site visit","Offer live","Follow-up"].map(x=><div key={x} style={{padding:13,border:"1px solid #2a3748",borderRadius:9}}><div style={{fontSize:10,color:"#8e9aaa"}}>{x}</div><strong style={{display:"block",marginTop:5,fontSize:14}}>Ready</strong></div>)}</div></div></div>
  <div style={{display:"grid",gridTemplateColumns:"1.4fr .8fr",gap:18}}><div className="card panel"><div className="panel-head"><div><h2>Customer modules</h2><div className="panel-note">Packages can be assembled per business and budget.</div></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}>{modules.map(m=>{const Icon=m.icon;return <button key={m.key} onClick={()=>setSelected(m.key)} style={{textAlign:"left",border:`1px solid ${selected===m.key?"#b9c9f7":"var(--line)"}`,background:selected===m.key?"var(--blue-soft)":"#fff",borderRadius:11,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div style={{width:34,height:34,borderRadius:9,background:"#eef3ff",display:"grid",placeItems:"center",color:"var(--blue)"}}><Icon size={16}/></div><span className={`badge ${m.status==="Foundation"?"hot":"muted"}`}>{m.status}</span></div><strong style={{display:"block",fontSize:13,marginTop:11}}>{m.title}</strong><p style={{color:"var(--muted)",fontSize:10,lineHeight:1.5,marginTop:5}}>{m.description}</p><div style={{marginTop:10,fontSize:10,fontWeight:700,color:"var(--blue)"}}>{m.price} package <ChevronRight size={11} style={{verticalAlign:"-2px"}}/></div></button>})}</div></div>
   <div className="card panel"><div className="panel-head"><h2>Selected module</h2><Bot size={16} color="var(--muted)"/></div>{(()=>{const m=modules.find(x=>x.key===selected)!;const Icon=m.icon;return <><div style={{width:42,height:42,borderRadius:10,background:"var(--blue-soft)",display:"grid",placeItems:"center",color:"var(--blue)"}}><Icon size={19}/></div><h2 style={{marginTop:14}}>{m.title}</h2><p className="sub" style={{fontSize:12}}>{m.description}</p><div style={{marginTop:18,padding:12,borderRadius:9,background:"var(--green-soft)",color:"var(--green)",fontSize:11}}><CheckCircle2 size={13} style={{verticalAlign:"-2px",marginRight:5}}/>Owner stays in control.</div><div style={{marginTop:14,display:"grid",gap:8}}>{["Simple setup","Hindi + English ready","Human handoff","Activity history"].map(x=><div key={x} style={{fontSize:11}}><CheckCircle2 size={13} color="var(--green)" style={{verticalAlign:"-2px",marginRight:6}}/>{x}</div>)}</div></>})()}</div></div>
  <div className="card panel" style={{marginTop:18}}><div className="panel-head"><h2>Package ladder</h2><WalletCards size={16} color="var(--muted)"/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[["Starter","₹3–7k setup","Lead capture + basic follow-up + simple customer page"],["Growth","₹10–25k setup","WhatsApp + offers + appointments + reviews"],["Premium","Custom","Voice agent + advanced automation + integrations + analytics"]].map(([a,b,c])=><div key={a} style={{padding:16,border:"1px solid var(--line)",borderRadius:10}}><strong>{a}</strong><div style={{color:"var(--blue)",fontWeight:800,fontSize:14,marginTop:7}}>{b}</div><p className="panel-note" style={{lineHeight:1.5,marginTop:6}}>{c}</p></div>)}</div></div>
 </main>
}
