"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Bot, CalendarDays, CheckCircle2, MessageCircle, Phone, Star, Users, WalletCards, Clock3, UserRound } from "lucide-react";
import { loadProspects, workspaceEventName, type WorkspaceProspect } from "@/lib/workspace";
import { businessOsEventName, loadAppointments, loadLeads, updateAppointment, updateLead, type AppointmentStatus, type BusinessAppointment, type BusinessLead } from "@/lib/businessos";

type Module={key:string;icon:typeof Users;title:string;description:string;status:"Live foundation"|"Build next";price:string};
const modules:Module[]=[
 {key:"leads",icon:Users,title:"Lead Inbox",description:"Capture enquiries into one owner-controlled queue with status, source and next action.",status:"Live foundation",price:"Starter"},
 {key:"appointments",icon:CalendarDays,title:"Appointments & Site Visits",description:"Request, confirm, reschedule and track appointments without losing conversation history.",status:"Live foundation",price:"Starter"},
 {key:"offers",icon:WalletCards,title:"Offers & Campaigns",description:"Create local offers in English, Hindi or Hinglish and prepare them for approved channels.",status:"Build next",price:"Growth"},
 {key:"messaging",icon:MessageCircle,title:"WhatsApp Inbox",description:"Centralize conversations with templates, quick replies and human handoff.",status:"Build next",price:"Growth"},
 {key:"voice",icon:Phone,title:"Calling / Voice Agent",description:"Optional Hindi + English receptionist for qualified inbound enquiries and approved flows.",status:"Build next",price:"Premium"},
 {key:"reviews",icon:Star,title:"Reviews & Reactivation",description:"Ask happy customers for reviews and bring past customers back with relevant offers.",status:"Build next",price:"Growth"},
 {key:"ai",icon:Bot,title:"AI Assistant",description:"Summarize leads, suggest replies and surface next actions without taking control away.",status:"Build next",price:"Premium"},
];

const leadStatuses: BusinessLead["status"][]=["New","Contacted","Qualified","Follow-up","Converted","Lost"];
const appointmentStatuses: AppointmentStatus[]=["Requested","Confirmed","Rescheduled","Completed","Cancelled"];

export default function BusinessOSPage(){
 const [selected,setSelected]=useState("leads"),[tab,setTab]=useState("inbox"),[prospects,setProspects]=useState<WorkspaceProspect[]>([]),[leads,setLeads]=useState<BusinessLead[]>([]),[appointments,setAppointments]=useState<BusinessAppointment[]>([]);
 const refresh=()=>{setProspects(loadProspects());setLeads(loadLeads());setAppointments(loadAppointments())};
 useEffect(()=>{refresh();window.addEventListener(workspaceEventName(),refresh);window.addEventListener(businessOsEventName(),refresh);return()=>{window.removeEventListener(workspaceEventName(),refresh);window.removeEventListener(businessOsEventName(),refresh)}},[]);
 const current=useMemo(()=>modules.find(x=>x.key===selected)!,[selected]);
 const activeLeads=leads.filter(x=>!(["Converted","Lost"] as string[]).includes(x.status)).length;
 const activeAppointments=appointments.filter(x=>!(["Completed","Cancelled"] as string[]).includes(x.status)).length;
 const displayLeads=leads.length?leads:prospects.slice(0,4).map(p=>({id:p.id,name:p.name,intent:p.nextAction,channel:"Manual" as const,status:"New" as const,prospectId:p.id,createdAt:p.createdAt,updatedAt:p.updatedAt||p.createdAt}));
 return <main className="content" style={{maxWidth:1280,margin:"0 auto"}}>
  <div className="header"><div><Link href="/" className="btn" style={{textDecoration:"none",display:"inline-block",marginBottom:14}}><ArrowLeft size={14} style={{verticalAlign:"-2px",marginRight:6}}/>ProspectOS</Link><h1>BusinessOS</h1><p className="sub">The customer-facing operating system we sell to Indian local businesses.</p></div><span className="badge hot"><CheckCircle2 size={12} style={{verticalAlign:"-2px",marginRight:4}}/>Owner-controlled</span></div>
  <div className="card panel" style={{background:"#101722",color:"#fff",marginBottom:18}}><div style={{display:"grid",gridTemplateColumns:"1.25fr 1fr",gap:24,alignItems:"center"}}><div><span style={{fontSize:10,letterSpacing:".12em",fontWeight:800,color:"#8e9aaa"}}>CUSTOMER PROMISE</span><h2 style={{fontFamily:"Manrope",fontSize:26,marginTop:8}}>“Aapka business, aapke control mein.”</h2><p style={{color:"#aeb8c6",fontSize:12,lineHeight:1.6,marginTop:8}}>One place for leads, appointments, offers, follow-ups and customer conversations. AI assists; the owner approves.</p></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:9}}>{[["Active leads",activeLeads],["Appointments",activeAppointments],["Offers",0],["Follow-ups",leads.filter(p=>p.status==="Follow-up").length]].map(([x,v])=><div key={String(x)} style={{padding:13,border:"1px solid #2a3748",borderRadius:9}}><div style={{fontSize:10,color:"#8e9aaa"}}>{x}</div><strong style={{display:"block",marginTop:5,fontSize:14}}>{v}</strong></div>)}</div></div></div>
  <div style={{display:"grid",gridTemplateColumns:"1.4fr .8fr",gap:18}}><div className="card panel"><div className="panel-head"><div><h2>Customer modules</h2><div className="panel-note">Build the customer product while ProspectOS keeps feeding it opportunities.</div></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}>{modules.map(m=>{const Icon=m.icon;return <button key={m.key} onClick={()=>setSelected(m.key)} style={{textAlign:"left",border:`1px solid ${selected===m.key?"#b9c9f7":"var(--line)"}`,background:selected===m.key?"var(--blue-soft)":"#fff",borderRadius:11,padding:14}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><div style={{width:34,height:34,borderRadius:9,background:"#eef3ff",display:"grid",placeItems:"center",color:"var(--blue)"}}><Icon size={16}/></div><span className={`badge ${m.status==="Live foundation"?"hot":"muted"}`}>{m.status}</span></div><strong style={{display:"block",fontSize:13,marginTop:11}}>{m.title}</strong><p style={{color:"var(--muted)",fontSize:10,lineHeight:1.5,marginTop:5}}>{m.description}</p><div style={{marginTop:10,fontSize:10,fontWeight:700,color:"var(--blue)"}}>{m.price} package</div></button>})}</div></div>
   <div className="card panel"><div className="panel-head"><h2>{current.title}</h2><current.icon size={16} color="var(--muted)"/></div><p className="sub" style={{fontSize:12}}>{current.description}</p>
   {(current.key==="leads"||current.key==="appointments")&&<div style={{marginTop:18}}><div style={{display:"flex",gap:6,marginBottom:12}}>{["inbox","appointments"].map(x=><button key={x} className={`badge ${tab===x?"hot":"muted"}`} onClick={()=>setTab(x)}>{x}</button>)}</div>
   {tab==="inbox"&&<div style={{display:"grid",gap:8}}>{displayLeads.slice(0,6).map(l=><div key={l.id} style={{padding:11,border:"1px solid var(--line)",borderRadius:9}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong style={{fontSize:11}}>{l.name}</strong><select value={l.status} onChange={e=>updateLead(l.id,{status:e.target.value as BusinessLead["status"]})} className="select" style={{fontSize:10,padding:"4px 7px"}}>{leadStatuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="panel-note" style={{marginTop:4}}>{l.intent} · {l.channel}</div></div>)}</div>}
   {tab==="appointments"&&<div style={{display:"grid",gap:8}}>{appointments.length===0?<div style={{padding:14,borderRadius:9,background:"var(--blue-soft)",fontSize:11}}><Clock3 size={13} style={{verticalAlign:"-2px",marginRight:5}}/>No appointment requests yet. Use the Demo Factory to create a real site-visit request.</div>:appointments.slice(0,6).map(a=><div key={a.id} style={{padding:11,border:"1px solid var(--line)",borderRadius:9}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong style={{fontSize:11}}>{a.customerName}</strong><select value={a.status} onChange={e=>updateAppointment(a.id,{status:e.target.value as AppointmentStatus})} className="select" style={{fontSize:10,padding:"4px 7px"}}>{appointmentStatuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="panel-note" style={{marginTop:4}}>{a.type} · {new Date(a.scheduledAt).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</div><div className="business-meta" style={{marginTop:4}}>{a.notes||"No notes"}</div></div>)}</div>}
   </div>}
   {current.key!=="leads"&&current.key!=="appointments"&&<div style={{marginTop:18,padding:14,borderRadius:9,background:"var(--blue-soft)",fontSize:11}}><CheckCircle2 size={13} color="var(--green)" style={{verticalAlign:"-2px",marginRight:5}}/>Module contract defined. UI, data model and automation connectors can now be implemented independently.</div>}
   <div style={{marginTop:16,padding:12,borderRadius:9,background:"var(--green-soft)",color:"var(--green)",fontSize:11}}>Human handoff stays available at every stage.</div></div></div>
  <div className="card panel" style={{marginTop:18}}><div className="panel-head"><div><h2>Live BusinessOS queue</h2><div className="panel-note">These records are generated by customer/demo actions and remain owner-controlled.</div></div><UserRound size={16} color="var(--muted)"/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:18}}><div><strong style={{fontSize:12}}>Recent leads</strong>{leads.length===0?<p className="panel-note" style={{marginTop:8}}>No customer-generated leads yet.</p>:<div style={{display:"grid",gap:7,marginTop:8}}>{leads.slice(0,5).map(l=><div key={l.id} style={{padding:10,border:"1px solid var(--line)",borderRadius:8}}><strong style={{fontSize:11}}>{l.name}</strong><div className="business-meta">{l.intent} · {l.channel} · {l.status}</div></div>)}</div>}</div><div><strong style={{fontSize:12}}>Upcoming appointments</strong>{appointments.filter(a=>a.status!=="Cancelled").slice(0,5).map(a=><div key={a.id} style={{padding:10,border:"1px solid var(--line)",borderRadius:8,marginTop:7}}><strong style={{fontSize:11}}>{a.customerName}</strong><div className="business-meta">{a.type} · {new Date(a.scheduledAt).toLocaleString("en-IN",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})} · {a.status}</div></div>)}{appointments.length===0&&<p className="panel-note" style={{marginTop:8}}>No appointments yet.</p>}</div></div></div>
  <div className="card panel" style={{marginTop:18}}><div className="panel-head"><h2>Package ladder</h2><WalletCards size={16} color="var(--muted)"/></div><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{[["Starter","₹3–7k setup","Lead capture + basic follow-up + customer page"],["Growth","₹10–25k setup","WhatsApp + offers + appointments + reviews"],["Premium","Custom","Voice + advanced automation + integrations + analytics"]].map(([a,b,c])=><div key={a} style={{padding:16,border:"1px solid var(--line)",borderRadius:10}}><strong>{a}</strong><div style={{color:"var(--blue)",fontWeight:800,fontSize:14,marginTop:7}}>{b}</div><p className="panel-note" style={{lineHeight:1.5,marginTop:6}}>{c}</p></div>)}</div></div>
 </main>
}
