"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarClock, CheckCircle2, ChevronRight, MessageCircle, Phone, Plus, Search, Target, UserRound } from "lucide-react";

type Stage = "New" | "Contacted" | "Interested" | "Demo" | "Won";
type Lead = { id:number; name:string; business:string; vertical:string; location:string; score:number; stage:Stage; next:string; channel:string };

const initial: Lead[] = [
  {id:1,name:"Amit Sharma",business:"Kabira Realty",vertical:"Real Estate",location:"Ghaziabad",score:100,stage:"Demo",next:"Send personalized demo",channel:"WhatsApp"},
  {id:2,name:"Jindal Alfatech",business:"Jindal Alfatech Realty",vertical:"Real Estate",location:"Greater Noida",score:86,stage:"Interested",next:"Follow up tomorrow",channel:"Call"},
  {id:3,name:"Clinic Manager",business:"Arya Dental Care",vertical:"Dental",location:"Greater Noida",score:78,stage:"Contacted",next:"Share appointment demo",channel:"WhatsApp"},
  {id:4,name:"Property Desk",business:"JMD Real Estate",vertical:"Real Estate",location:"Ghaziabad",score:33,stage:"New",next:"Verify opportunity",channel:"—"},
];
const stages: Stage[] = ["New","Contacted","Interested","Demo","Won"];

export default function SalesPage(){
 const [leads,setLeads]=useState(initial); const [query,setQuery]=useState("");
 const visible=useMemo(()=>leads.filter(l=>`${l.name} ${l.business} ${l.vertical} ${l.location}`.toLowerCase().includes(query.toLowerCase())),[leads,query]);
 const move=(id:number,stage:Stage)=>setLeads(xs=>xs.map(x=>x.id===id?{...x,stage}:x));
 return <main className="content" style={{maxWidth:1450,margin:"0 auto"}}>
  <div className="header"><div><Link href="/" className="btn" style={{textDecoration:"none",display:"inline-block",marginBottom:14}}><ArrowLeft size={14} style={{verticalAlign:"-2px",marginRight:6}}/>ProspectOS</Link><h1>Sales Command Center</h1><p className="sub">Turn verified opportunities into human conversations, demos and customers.</p></div><div className="actions"><Link href="/discovery" className="btn"><Plus size={14} style={{verticalAlign:"-2px",marginRight:5}}/>Find prospects</Link><Link href="/demo" className="btn primary">Create demo</Link></div></div>
  <div className="stats"><div className="card stat"><div className="stat-top"><span>Active opportunities</span><Target size={15}/></div><div className="stat-value">{leads.length}</div><div className="stat-note">Evidence-backed queue</div></div><div className="card stat"><div className="stat-top"><span>Interested + demo</span><CheckCircle2 size={15}/></div><div className="stat-value">{leads.filter(l=>l.stage==="Interested"||l.stage==="Demo").length}</div><div className="stat-note">Ready for follow-up</div></div><div className="card stat"><div className="stat-top"><span>Follow-ups</span><CalendarClock size={15}/></div><div className="stat-value">3</div><div className="stat-note neutral">Next-action driven</div></div><div className="card stat"><div className="stat-top"><span>Won</span><CheckCircle2 size={15}/></div><div className="stat-value">{leads.filter(l=>l.stage==="Won").length}</div><div className="stat-note neutral">Connect BusinessOS after close</div></div></div>
  <div className="card toolbar"><div style={{position:"relative",flex:1}}><Search size={15} style={{position:"absolute",left:12,top:10,color:"#8a95a5"}}/><input className="search" style={{paddingLeft:36}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search prospect, business, vertical or location…"/></div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(5,minmax(180px,1fr))",gap:12,marginTop:14,overflowX:"auto"}}>
   {stages.map(stage=><div key={stage} className="card" style={{padding:12,minHeight:330}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><strong style={{fontSize:12}}>{stage}</strong><span className="badge muted">{visible.filter(l=>l.stage===stage).length}</span></div>{visible.filter(l=>l.stage===stage).map(l=><div key={l.id} style={{background:"#fff",border:"1px solid var(--line)",borderRadius:10,padding:12,marginBottom:9,boxShadow:"0 5px 15px rgba(23,32,42,.04)"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong style={{fontSize:12}}>{l.business}</strong><span className={`score ${l.score>=70?"high":l.score>=40?"medium":"low"}`}>{l.score}</span></div><div className="business-meta">{l.name} · {l.location}</div><div style={{marginTop:10,fontSize:10,color:"var(--muted)"}}><UserRound size={11} style={{verticalAlign:"-2px",marginRight:4}}/>{l.vertical}</div><div style={{marginTop:7,fontSize:10,color:"var(--muted)"}}><MessageCircle size={11} style={{verticalAlign:"-2px",marginRight:4}}/>{l.channel}</div><div style={{marginTop:10,paddingTop:9,borderTop:"1px solid var(--line)",fontSize:10,fontWeight:700}}>{l.next}</div><select value={l.stage} onChange={e=>move(l.id,e.target.value as Stage)} className="select" style={{width:"100%",marginTop:9,fontSize:10}}>{stages.map(s=><option key={s}>{s}</option>)}</select><button className="link-btn" style={{marginTop:9,padding:0}}>Open prospect <ChevronRight size={11} style={{verticalAlign:"-2px"}}/></button></div>)}</div>)}
  </div>
  <div className="grid2" style={{marginTop:18}}><div className="card panel"><div className="panel-head"><h2>Next-action queue</h2><CalendarClock size={16} color="var(--muted)"/></div>{leads.filter(l=>l.stage!=="Won").slice(0,4).map(l=><div className="opportunity" key={l.id}><div className="dot"/><div style={{flex:1}}><strong>{l.next}</strong><p>{l.business} · {l.channel} · {l.location}</p></div><span className="badge muted">{l.stage}</span></div>)}</div><div className="card panel"><div className="panel-head"><h2>Outreach guardrails</h2><Phone size={16} color="var(--muted)"/></div><div className="opportunity"><div className="dot" style={{background:"var(--green)"}}/><div><strong>Personalized before contact</strong><p>Use verified evidence and a relevant demo, never a generic blast.</p></div></div><div className="opportunity"><div className="dot" style={{background:"var(--green)"}}/><div><strong>Human approval</strong><p>Automated calling/messaging should only activate through a compliant, consent-aware workflow.</p></div></div><div className="opportunity"><div className="dot" style={{background:"var(--green)"}}/><div><strong>Track outcome</strong><p>Every contact should produce a next action: follow up, demo, won or disqualified.</p></div></div></div></div>
 </main>
}
