"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, CalendarClock, CheckCircle2, ChevronRight, MessageCircle, Plus, Search, Target, UserRound } from "lucide-react";
import { loadProspects, updateProspect, workspaceEventName, type ProspectStage, type WorkspaceProspect } from "@/lib/workspace";
const stages:ProspectStage[]=["New","Contacted","Interested","Demo","Won","Disqualified"];
const demo:WorkspaceProspect[]=[
 {id:"demo-1",name:"Kabira Realty",business:"Kabira Realty",category:"Real Estate",location:"Ghaziabad",score:100,gaps:3,stage:"Demo",nextAction:"Send personalized demo",createdAt:new Date().toISOString(),source:"Manual"},
 {id:"demo-2",name:"Jindal Alfatech",business:"Jindal Alfatech Realty",category:"Real Estate",location:"Greater Noida",score:86,gaps:2,stage:"Interested",nextAction:"Follow up tomorrow",createdAt:new Date().toISOString(),source:"Manual"},
 {id:"demo-3",name:"Arya Dental Care",business:"Arya Dental Care",category:"Dental",location:"Greater Noida",score:78,gaps:2,stage:"Contacted",nextAction:"Share appointment demo",createdAt:new Date().toISOString(),source:"Manual"},
];
export default function SalesPage(){
 const [leads,setLeads]=useState<WorkspaceProspect[]>([]),[query,setQuery]=useState("");
 useEffect(()=>{const refresh=()=>{const saved=loadProspects();setLeads(saved.length?saved:demo)};refresh();window.addEventListener(workspaceEventName(),refresh);return()=>window.removeEventListener(workspaceEventName(),refresh)},[]);
 const visible=useMemo(()=>leads.filter(l=>`${l.name} ${l.category} ${l.location}`.toLowerCase().includes(query.toLowerCase())),[leads,query]);
 const move=(id:string,stage:ProspectStage)=>{const next=stage==="Won"?"Onboard customer":stage==="Demo"?"Prepare personalized demo":stage==="Interested"?"Schedule follow-up":"Review opportunity";updateProspect(id,{stage,nextAction:next});setLeads(loadProspects())};
 return <main className="content" style={{maxWidth:1500,margin:"0 auto"}}>
  <div className="header"><div><Link href="/" className="btn" style={{textDecoration:"none",display:"inline-block",marginBottom:14}}><ArrowLeft size={14} style={{verticalAlign:"-2px",marginRight:6}}/>ProspectOS</Link><h1>Sales Command Center</h1><p className="sub">Every saved discovery prospect can now move through one shared sales lifecycle.</p></div><div className="actions"><Link href="/discovery" className="btn"><Plus size={14} style={{verticalAlign:"-2px",marginRight:5}}/>Find prospects</Link><Link href="/demo" className="btn primary">Create demo</Link></div></div>
  <div className="stats"><div className="card stat"><div className="stat-top"><span>Pipeline</span><Target size={15}/></div><div className="stat-value">{leads.filter(l=>l.stage!=="Won"&&l.stage!=="Disqualified").length}</div><div className="stat-note">Active prospects</div></div><div className="card stat"><div className="stat-top"><span>Interested + demo</span><CheckCircle2 size={15}/></div><div className="stat-value">{leads.filter(l=>l.stage==="Interested"||l.stage==="Demo").length}</div><div className="stat-note">Ready for follow-up</div></div><div className="card stat"><div className="stat-top"><span>Action queue</span><CalendarClock size={15}/></div><div className="stat-value">{leads.filter(l=>l.stage!=="Won"&&l.stage!=="Disqualified").length}</div><div className="stat-note neutral">One next action per prospect</div></div><div className="card stat"><div className="stat-top"><span>Won</span><CheckCircle2 size={15}/></div><div className="stat-value">{leads.filter(l=>l.stage==="Won").length}</div><div className="stat-note neutral">Ready for BusinessOS onboarding</div></div></div>
  <div className="card toolbar"><div style={{position:"relative",flex:1}}><Search size={15} style={{position:"absolute",left:12,top:10,color:"#8a95a5"}}/><input className="search" style={{paddingLeft:36}} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search prospect, business, vertical or location…"/></div></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(180px,1fr))",gap:12,marginTop:14,overflowX:"auto"}}>{stages.map(stage=><div key={stage} className="card" style={{padding:12,minHeight:340}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><strong style={{fontSize:12}}>{stage}</strong><span className="badge muted">{visible.filter(l=>l.stage===stage).length}</span></div>{visible.filter(l=>l.stage===stage).map(l=><div key={l.id} style={{background:"#fff",border:"1px solid var(--line)",borderRadius:10,padding:12,marginBottom:9,boxShadow:"0 5px 15px rgba(23,32,42,.04)"}}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong style={{fontSize:12}}>{l.name}</strong><span className={`score ${l.score>=70?"high":l.score>=40?"medium":"low"}`}>{l.score}</span></div><div className="business-meta">{l.location} · {l.category}</div><div style={{marginTop:9,fontSize:10,color:"var(--muted)"}}><UserRound size={11} style={{verticalAlign:"-2px",marginRight:4}}/>{l.gaps} verified gaps</div><div style={{marginTop:7,fontSize:10,color:"var(--muted)"}}><MessageCircle size={11} style={{verticalAlign:"-2px",marginRight:4}}/>{l.nextAction}</div><select value={l.stage} onChange={e=>move(l.id,e.target.value as ProspectStage)} className="select" style={{width:"100%",marginTop:9,fontSize:10}}>{stages.map(s=><option key={s}>{s}</option>)}</select><Link href="/business" className="link-btn" style={{display:"inline-block",marginTop:9,textDecoration:"none"}}>Open BusinessOS <ChevronRight size={11} style={{verticalAlign:"-2px"}}/></Link></div>)}</div>)}</div>
  <div className="grid2" style={{marginTop:18}}><div className="card panel"><div className="panel-head"><h2>Next-action queue</h2><CalendarClock size={16} color="var(--muted)"/></div>{leads.filter(l=>l.stage!=="Won"&&l.stage!=="Disqualified").slice(0,6).map(l=><div className="opportunity" key={l.id}><div className="dot"/><div style={{flex:1}}><strong>{l.nextAction}</strong><p>{l.name} · {l.location} · score {l.score}</p></div><span className="badge muted">{l.stage}</span></div>)}</div><div className="card panel"><div className="panel-head"><h2>Outreach guardrails</h2><Target size={16} color="var(--muted)"/></div>{[["Evidence before contact","Use verified evidence and a relevant demo, never a generic blast."],["Human approval","Messaging/calling only activates through a compliant, consent-aware workflow."],["Track outcome","Every contact ends with a next action: follow up, demo, won or disqualified."]].map(([a,b])=><div className="opportunity" key={a}><div className="dot" style={{background:"var(--green)"}}/><div><strong>{a}</strong><p>{b}</p></div></div>)}</div></div>
 </main>
}
